In [1]:
!pip install neo4j
import neo4j
import pandas as pd

Collecting neo4j
  Downloading https://files.pythonhosted.org/packages/0b/22/9b6d28613e8a564b9e82cf3b871b6df1f58a99cf5ac8a100439f9e895b5f/neo4j-4.3.1.tar.gz (74kB)
     |████████████████████████████████| 81kB 7.8MB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from neo4j) (2018.9)
Building wheels for collected packages: neo4j
  Building wheel for neo4j (setup.py) ... done
  Created wheel for neo4j: filename=neo4j-4.3.1-cp37-none-any.whl size=99332 sha256=4de54c8f8da393758b80a641924e8c657bb341f7119e45d0efdf53f0b32e5f85
  Stored in directory: /root/.cache/pip/wheels/23/13/72/0cc2405898bd9a7baef6512df3abf83873da9ba48c04acc818
Successfully built neo4j
Installing collected packages: neo4j
Successfully installed neo4j-4.3.1

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [4]:
df = pd.read_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/winemag-data-130k-v2.csv')
print(df.shape)
df.head(3)

(129971, 14)

   ID   country  ...         variety               winery
0   0     Italy  ...     White Blend              Nicosia
1   1  Portugal  ...  Portuguese Red  Quinta dos Avidagos
2   2        US  ...      Pinot Gris            Rainstorm

[3 rows x 14 columns]

In [5]:
#Creates country
country= df[['ID','designation','region_2','region_1','province','country']]
country.head(3)

   ID   designation  ...           province   country
0   0  Vulkà Bianco  ...  Sicily & Sardinia     Italy
1   1      Avidagos  ...              Douro  Portugal
2   2           NaN  ...             Oregon        US

[3 rows x 6 columns]

In [6]:
province= df[['ID','designation','region_2','region_1','province']]
province.head(3)

   ID   designation           region_2           region_1           province
0   0  Vulkà Bianco                NaN               Etna  Sicily & Sardinia
1   1      Avidagos                NaN                NaN              Douro
2   2           NaN  Willamette Valley  Willamette Valley             Oregon

In [7]:
region1= df[['ID','designation','region_2','region_1']]
region1.head(3)

   ID   designation           region_2           region_1
0   0  Vulkà Bianco                NaN               Etna
1   1      Avidagos                NaN                NaN
2   2           NaN  Willamette Valley  Willamette Valley

In [8]:
region2= df[['ID','designation','region_2']]
region2.head(3)

   ID   designation           region_2
0   0  Vulkà Bianco                NaN
1   1      Avidagos                NaN
2   2           NaN  Willamette Valley

In [9]:
designation= df[['ID','designation']]
designation.head(3)

   ID   designation
0   0  Vulkà Bianco
1   1      Avidagos
2   2           NaN

In [10]:
price=df[['ID','price']]
price.head(3)

   ID  price
0   0    NaN
1   1   15.0
2   2   14.0

In [11]:
points=df[['ID','points']]
points.head(3)

   ID  points
0   0      87
1   1      87
2   2      87

In [12]:
winery=df[['ID','winery']]
winery.head(3)

   ID               winery
0   0              Nicosia
1   1  Quinta dos Avidagos
2   2            Rainstorm

In [13]:
variety=df[['ID','variety']]
variety.head(3)

   ID         variety
0   0     White Blend
1   1  Portuguese Red
2   2      Pinot Gris

In [14]:
#Created the main title node out of the rest of the variables
title=df[['ID','title','description']]
title.head(3)

   ID  ...                                        description
0   0  ...  Aromas include tropical fruit, broom, brimston...
1   1  ...  This is ripe and fruity, a wine that is smooth...
2   2  ...  Tart and snappy, the flavors of lime flesh and...

[3 rows x 3 columns]

In [15]:
title.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/title.csv', index=False)
variety.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/variety.csv', index=False)
winery.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/winery.csv', index=False)
points.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/points.csv', index=False)
price.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/price.csv', index=False)
designation.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/designation.csv', index=False)
region2.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/region2.csv', index=False)
region1.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/region1.csv', index=False)
province.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/province.csv', index=False)
country.to_csv('/content/gdrive/MyDrive/Summer 2021/DSBA 6520/Project/country.csv', index=False)